package control;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;

import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


@SuppressWarnings("serial")
public class AlugarCarro extends javax.swing.JInternalFrame {

    /** Creates new form DevolverCarro 
     * @param jdpPrincipal */
    public AlugarCarro(JDesktopPane jdpPrincipal) {
        initComponents();

        java.util.Date theDate = new java.util.Date();
        SimpleDateFormat format = new SimpleDateFormat("dd-MM-yyyy");
        jTextField4.setText(format.format(theDate));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();     
        
        jScrollPane2 = new javax.swing.JScrollPane();
        
        jTable1 = new javax.swing.JTable();
        


        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Return Car");
        getContentPane().setLayout(null);

        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 60, 70, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(100, 60, 140, 30);

        jButton1.setText("Search By ID");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(250, 20, 120, 30);
        
        jButton3.setText("Alugar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(250, 100, 120, 30);

        jLabel5.setText("Customer ID");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 20, 70, 30);

        jButton4.setText("Search by Name");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(250, 60, 120, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "customerid", "name", "phoneno", "address", "Car Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(390, 20, 470, 320);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(100, 20, 140, 30);

        jLabel1.setText("Car Details");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 100, 120, 40);

        jLabel3.setText("Company");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 240, 60, 30);

        jTextField3.setEditable(false);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(100, 240, 170, 30);

        jLabel4.setText("Return Date : ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 350, 110, 30);

        jTextField4.setEditable(false);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(160, 350, 170, 30);

        jLabel6.setText("Number");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 140, 60, 30);

        jTextField5.setEditable(false);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(100, 140, 170, 30);

        jLabel7.setText("Model");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 190, 60, 30);

        jTextField6.setEditable(false);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(100, 190, 170, 30);

        jLabel8.setText("Booking Date :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 310, 90, 30);

        jTextField7.setEditable(false);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(160, 310, 170, 30);

        jButton2.setText("Car Returned");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(550, 360, 190, 40);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-917)/2, (screenSize.height-462)/2, 917, 462);
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


    String path = "jdbc:mysql://localhost/";
    String place = "VcAluga";
    try {
        Class.forName("com.mysql.jdbc.Driver");

        Connection myconnect = DriverManager.getConnection(path + place,  "fam1709","17091991");
        try {
            String p = "select * from veiculo where locador=?";
            PreparedStatement mystatement = myconnect.prepareStatement(p);
            mystatement.setString(1, jTextField2.getText());
            ResultSet rs = mystatement.executeQuery();
            if (rs.next()) {
                jTextField1.setText(rs.getString("veiculo.locador"));
                jTextField5.setText(rs.getString("veiculo.placa"));

                jTextField6.setText(rs.getString("veiculo.marca"));
                jTextField3.setText(rs.getString("veiculo.modelo"));

                jTextField7.setText(rs.getString("veiculo.data"));

            } else {
                JOptionPane.showMessageDialog(rootPane, "no records found");
            }




        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "error in Query" + ex.getMessage());
        }


    } catch (Exception ex) {
        JOptionPane.showMessageDialog(rootPane, "error in connection" + ex.getMessage());
    }


}//GEN-LAST:event_jButton1ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    String path = "jdbc:mysql://localhost/";
    String place = "VcAluga";
    try {
        Class.forName("com.mysql.jdbc.Driver");

        Connection myconnect = DriverManager.getConnection(path + place,  "fam1709","17091991");
        try {
            String p = "select * from addcustomer,taxiservice where addcustomer.carnum=taxiservice.carnumber and addcustomer.name LIKE '%" + jTextField1.getText() + "%' and taxiservice.status='rented'";
            PreparedStatement mystatement = myconnect.prepareStatement(p);
            DefaultTableModel tbl = (DefaultTableModel) jTable1.getModel();
            String id = "", name = "", phn = "", add = "";
            ResultSet rs = mystatement.executeQuery();
            if (rs.next()) {
                tbl.setRowCount(0);

                do {
                    id = rs.getString("customerid");
                    name = rs.getString("name");
                    phn = rs.getString("phoneno");
                    add = rs.getString("address");

                    tbl.addRow(new Object[]{id, name, phn, add, rs.getString("carnum")});

                } while (rs.next());

            } else {
                JOptionPane.showMessageDialog(rootPane, "No records found");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "error in Query" + ex.getMessage());
        }


    } catch (Exception ex) {
        JOptionPane.showMessageDialog(rootPane, "error in connection" + ex.getMessage());
    }




    // TODO add your handling code here:
}//GEN-LAST:event_jButton4ActionPerformed

private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    int r = jTable1.getSelectedRow();
    jTextField2.setText(jTable1.getValueAt(r, 0).toString());
    jButton1ActionPerformed(null);

    // TODO add your handling code here:
}//GEN-LAST:event_jTable1MouseClicked

/*
 * 
 * 
 * 			String f = "update veiculo set status = \"alugado\" where placa = ?";
        	String p = "update veiculo set locador = ? where placa=?";          
            PreparedStatement mystatement = myconnect.prepareStatement(p);
            PreparedStatement mystatement2 = myconnect.prepareStatement(f);
            mystatement.setString(1, jTextField5.getText());
            mystatement.setString2(1, jTextField2.getText());
            mystatement2.setString(2, jTextField5.getText());

            mystatement.executeUpdate();
            mystatement2.executeUpdate()
 * 
 * 			//nota: field 5 = placa, field 2 = nome 
 * 
 * 
 * */

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed



    String path = "jdbc:mysql://localhost/";
    String place = "VcAluga";

    try {
        Class.forName("com.mysql.jdbc.Driver");

        Connection myconnect = DriverManager.getConnection(path + place,  "fam1709","17091991");
        try {       
        	String f = "update veiculo set status = \"alugado\" where placa = ?";
        	String p = "update veiculo set locador = ? where placa=?";          
            PreparedStatement mystatement = myconnect.prepareStatement(f);
            PreparedStatement mystatement2 = myconnect.prepareStatement(p);
            mystatement.setString(1, jTextField5.getText()); //placa
            mystatement2.setString(1, jTextField2.getText()); //locador (customer)
            mystatement2.setString(2, jTextField5.getText());

            mystatement.executeUpdate();
            mystatement2.executeUpdate();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "error in updation customer : " + ex.getMessage());
        }


     
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(rootPane, "error in connection" + ex.getMessage());

    }



}

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed



    String path = "jdbc:mysql://localhost/";
    String place = "VcAluga";

    try {
        Class.forName("com.mysql.jdbc.Driver");

        Connection myconnect = DriverManager.getConnection(path + place,  "fam1709","17091991");
        try {       
        	String f = "update veiculo set status = \"desocupado\" where locador = ?";
        	String p = "update veiculo set locador = \"disponivel\" where locador=?";          
            PreparedStatement mystatement = myconnect.prepareStatement(p);
            PreparedStatement mystatement2 = myconnect.prepareStatement(f);
            //mystatement.setString(1, "disponivel");
            //mystatement.setString(2, "desocupado");
            mystatement.setString(1, jTextField2.getText());
            mystatement2.setString(1, jTextField2.getText());

            mystatement.executeUpdate();
            mystatement2.executeUpdate();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "error in updation customer : " + ex.getMessage());
        }


     
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(rootPane, "error in connection" + ex.getMessage());

    }



}//GEN-LAST:event_jButton2ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}