package control;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import model.ConnectionFactory;
import view.Tela_CadastroCliente;


public class ConsultarHabilitacao extends javax.swing.JInternalFrame {

	private static final long serialVeresultSetionUID = 1L;

	private JDesktopPane jdpPrincipal;
	
	private javax.swing.JButton btExcluir;
	private javax.swing.JButton btNovo;
	private javax.swing.JButton btPesquisar;
	private javax.swing.JButton btAlterar;
	private javax.swing.JButton btCancelar;
	private javax.swing.JButton btAtualizar;
	private javax.swing.JLabel jLabel;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jtHabilitacao;
	private javax.swing.JTextField txtNome;

	public ConsultarHabilitacao( JDesktopPane jdp ) {
		initComponents();
		jdpPrincipal = jdp;
		try {
			Connection connection = new ConnectionFactory().getConnection();
			String sql = "select * from habilitacao";
			// if(!txtNome.getText().equals(""))
			// sql = sql + " where Nome LIKE ? ";
			PreparedStatement statement = connection.prepareStatement( sql );
			if( !txtNome.getText().equals( "" ) )
				statement.setString( 1, "%" + txtNome.getText() + "%" );
			ResultSet resultSet = statement.executeQuery();
			DefaultTableModel model = ( DefaultTableModel ) jtHabilitacao.getModel();
			model.setNumRows( 0 );
			while( resultSet.next() ) {
				String[] linha = { resultSet.getString( "cpf_cliente" ), resultSet.getString( "nmr_registro" ), resultSet.getString( "tipo" ),
						resultSet.getString( "categoria" ),resultSet.getString( "data_exped" ),resultSet.getString( "data_validade" ) };
				model.addRow( linha );
			}

			statement.close();
			connection.close();
		} catch( SQLException e ) {
			JOptionPane.showMessageDialog( this, e );
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings( { "unchecked", "serial" } )

	private void initComponents() {

		jLabel = new javax.swing.JLabel();
		txtNome = new javax.swing.JTextField();
		btPesquisar = new javax.swing.JButton();
		btNovo = new javax.swing.JButton();
		btAlterar = new javax.swing.JButton();
		btExcluir = new javax.swing.JButton();
		btCancelar = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jtHabilitacao = new javax.swing.JTable();
		btAtualizar = new javax.swing.JButton();

		setClosable( true );
		setIconifiable( true );
		setMaximizable( true );
		setResizable( true );
		setTitle( "Consultar Habilitação" );

		jLabel.setText( "CPF:" );

		txtNome.addActionListener( new java.awt.event.ActionListener() {
			public void actionPerformed( java.awt.event.ActionEvent evt ) {
				btNomeActionPerformed( evt );
			}
		} );

		btPesquisar.setText( "Pesquisar" );
		btPesquisar.addActionListener( new java.awt.event.ActionListener() {
			public void actionPerformed( java.awt.event.ActionEvent evt ) {
				btPesquisarActionPerformed( evt );
			}
		} );

		btNovo.setText( "Novo" );
		btNovo.addActionListener( new java.awt.event.ActionListener() {
			public void actionPerformed( java.awt.event.ActionEvent evt ) {
				btNovoActionPerformed( evt );
			}
		} );

		btAlterar.setText( "Alterar" );
		btAlterar.addActionListener( new java.awt.event.ActionListener() {
			public void actionPerformed( java.awt.event.ActionEvent evt ) {
				btAlterarActionPerformed( evt );
			}
		} );

		/*btExcluir.setText( "Excluir" );
		btExcluir.addActionListener( new java.awt.event.ActionListener() {
			public void actionPerformed( java.awt.event.ActionEvent evt ) {
				btExcluirActionPerformed( evt );
			}
		} );*/

		btCancelar.setText( "Cancelar" );
		btCancelar.addActionListener( new java.awt.event.ActionListener() {
			public void actionPerformed( java.awt.event.ActionEvent evt ) {
				btCancelarActionPerformed( evt );
			}
		} );

		jtHabilitacao.setModel( new javax.swing.table.DefaultTableModel( new Object[][] {

		}, new String[] { "CPF", "Numero Registro", "Tipo", "Categoria","Data Expedição","Data Validade" } ) {
			boolean[] canEdit = new boolean[] { false, false, false, false, false,false};

			public boolean isCellEditable( int rowIndex, int columnIndex ) {
				return canEdit[columnIndex];
			}
		} );
		jScrollPane1.setViewportView( jtHabilitacao );

		btAtualizar.setText( "Atualizar" );
		btAtualizar.addActionListener( new java.awt.event.ActionListener() {
			public void actionPerformed( java.awt.event.ActionEvent evt ) {
				jButtonAtualizarActionPerformed( evt );
			}
		} );

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout( getContentPane() );
		getContentPane().setLayout( layout );
		layout.setHorizontalGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
				.addGroup( layout.createSequentialGroup().addContainerGap()
						.addGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
								.addComponent( jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE )
								.addGroup( layout.createSequentialGroup().addComponent( btPesquisar )
										.addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED ).addComponent( btNovo )
										.addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED ).addComponent( btAlterar )
										.addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED ).addComponent( btExcluir )
										.addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED ).addComponent( btAtualizar )
										.addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED ).addComponent( btCancelar )
										.addGap( 0, 0, Short.MAX_VALUE ) )
								.addGroup( layout.createSequentialGroup().addComponent( jLabel )
										.addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED ).addComponent( txtNome ) ) )
						.addContainerGap() ) );
		layout.setVerticalGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
				.addGroup( layout.createSequentialGroup().addContainerGap()
						.addGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE )
								.addComponent( txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE )
								.addComponent( jLabel ) )
						.addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED )
						.addGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE ).addComponent( btPesquisar )
								.addComponent( btNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE )
								.addComponent( btAlterar ).addComponent( btExcluir ).addComponent( btCancelar ).addComponent( btAtualizar ) )
						.addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED ).addComponent( jScrollPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE )
						.addContainerGap() ) );

		pack();
	}

	private void btNomeActionPerformed( java.awt.event.ActionEvent evt ) {
	
	}

	private void btCancelarActionPerformed( java.awt.event.ActionEvent evt ) {

	}

	private void btNovoActionPerformed( java.awt.event.ActionEvent evt ) {
		Tela_CadastroCliente cadastrarCliente = new Tela_CadastroCliente();
		jdpPrincipal.add( cadastrarCliente );
		cadastrarCliente.setVisible( true );
	}

	private void btPesquisarActionPerformed( java.awt.event.ActionEvent evt ) {
		
		try {
			Connection connection = new ConnectionFactory().getConnection();
			String sql = "select * from habilitacao ";
			if( !txtNome.getText().equals( "" ) )
				sql = sql + " where cpf_cliente LIKE ? ";
			PreparedStatement statement = connection.prepareStatement( sql );
			if( !txtNome.getText().equals( "" ) )
				statement.setString( 1, "%" + txtNome.getText() + "%" );
			ResultSet resultSet = statement.executeQuery();
			DefaultTableModel model = ( DefaultTableModel ) jtHabilitacao.getModel();
			model.setNumRows( 0 );
			while( resultSet.next() ) {
				String[] linha = { resultSet.getString( "cpf_cliente" ), resultSet.getString( "nmr_registro" ), resultSet.getString( "tipo" ),
						resultSet.getString( "categoria" ),resultSet.getString( "data_exped" ),resultSet.getString( "data_validade" ) };
				model.addRow( linha );
			}

			statement.close();
			connection.close();
		} catch( SQLException e ) {
			JOptionPane.showMessageDialog( this, e );
		}

	}

/*	private void btExcluirActionPerformed( java.awt.event.ActionEvent evt ) {
		try {
			Connection connection = new ConnectionFactory().getConnection();
			String sql = "delete from cliente where cpf = ?";
			PreparedStatement statement = connection.prepareStatement( sql );
			int linha = this.jtHabilitacao.getSelectedRow();
			statement.setString( 1, jtHabilitacao.getValueAt( linha, 0 ).toString() );
			statement.execute();
			statement.close();
			connection.close();
			DefaultTableModel model = ( DefaultTableModel ) jtHabilitacao.getModel();
			model.removeRow( linha );
			JOptionPane.showMessageDialog( this, "Cliente Excluído com Sucesso!" );
			this.setClosable( true );
		} catch( SQLException e ) {
			JOptionPane.showMessageDialog( this, e );
		}
	}
*/


	private void btAlterarActionPerformed( java.awt.event.ActionEvent evt ) {
		int linha = this.jtHabilitacao.getSelectedRow();
		int id = Integer.parseInt( jtHabilitacao.getValueAt( linha, 0 ).toString() );
		Tela_CadastroCliente cadastrarCliente = new Tela_CadastroCliente();
		jdpPrincipal.add( cadastrarCliente );
		cadastrarCliente.setVisible( true );
	}

	private void jButtonAtualizarActionPerformed( java.awt.event.ActionEvent evt ) {
		try {
			Connection con = new ConnectionFactory().getConnection();
			String sql = "select * from habilitacao ";
			// if(!txtNome.getText().equals(""))
			// sql = sql + " where Nome LIKE ? ";
			PreparedStatement statement = con.prepareStatement( sql );
			if( !txtNome.getText().equals( "" ) )
				statement.setString( 1, "%" + txtNome.getText() + "%" );
			ResultSet resultSet = statement.executeQuery();
			DefaultTableModel model = ( DefaultTableModel ) jtHabilitacao.getModel();
			model.setNumRows( 0 );
			while( resultSet.next() ) {
				String[] linha = { resultSet.getString( "cpf_cliente" ), resultSet.getString( "nmr_registro" ), resultSet.getString( "tipo" ),
						resultSet.getString( "categoria" ),resultSet.getString( "data_exped" ),resultSet.getString( "data_validade" ) };
				model.addRow( linha );
			}

			statement.close();
			con.close();
		} catch( SQLException e ) {
			JOptionPane.showMessageDialog( this, e );
		}
	}


}
