package control;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import java.util.Date.*;

import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

@SuppressWarnings("serial")
public class ConsultarCarro extends javax.swing.JInternalFrame {

    /** Creates new form ConsultarCarro 
     * @param jdpPrincipal */
    public ConsultarCarro(JDesktopPane jdpPrincipal) {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Ver Carros");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "locador", "tipo", "placa", "modelo", "marca", "filial", "anoFabricacao", "uso", "assentos","motor", "variacao","preco", "status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 130, 880, 320);

        jLabel10.setText("Select Company");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(150, 20, 90, 30);

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(240, 20, 120, 30);

        jButton3.setText("Ver Carros");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(490, 70, 190, 30);

        jLabel9.setText("Status");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(480, 20, 70, 30);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Passeio", "Carga" }));
        getContentPane().add(jComboBox6);
        jComboBox6.setBounds(240, 60, 120, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alugado", "Desocupado" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(550, 20, 130, 30);

        jLabel11.setText("Use as");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(150, 60, 70, 30);

        setBounds(0, 0, 934, 510);
    }// </editor-fold>//GEN-END:initComponents

private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
}//GEN-LAST:event_jTable1MouseClicked

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

    String path = "jdbc:mysql://localhost/";
    String place = "VcAluga";
    try {
        Class.forName("com.mysql.jdbc.Driver");

        Connection myconnect = DriverManager.getConnection(path + place,  "fam1709","17091991");
        try {
        	String q = "select * from veiculo where veiculo.marca=? and veiculo.uso=? and veiculo.status=? ";
            
            PreparedStatement mystatement = myconnect.prepareStatement(q);
            mystatement.setString(1, jComboBox2.getSelectedItem().toString().toLowerCase());
            mystatement.setString(2, jComboBox6.getSelectedItem().toString().toLowerCase());
            mystatement.setString(3, jComboBox1.getSelectedItem().toString().toLowerCase());


            DefaultTableModel mymodel = (DefaultTableModel) jTable1.getModel();
            String  locador, tipo,
            placa, modelo, marca, filial, anoFabricacao, uso,assentos,
            motor,variacao,preco,status;
            
            ResultSet rs = mystatement.executeQuery();
            mymodel.setRowCount(0);
            if (rs.next()) {
                do {

                    locador = rs.getString("locador");
                    tipo = rs.getString("tipo");
                    placa = rs.getString("placa");
                    modelo = rs.getString("modelo");
                    marca = rs.getString("marca");
                    filial = rs.getString("filial");
                    anoFabricacao = rs.getString("anoFabricacao");
                    uso = rs.getString("uso");
                    assentos = rs.getString("assentos");
                    motor = rs.getString("motor");
                    variacao = rs.getString("variacao");
                    preco = rs.getString("preco");
                    status = rs.getString("status");
         
                    

                    mymodel.addRow(new Object[]{locador, tipo, placa, modelo, marca, 
                    		filial, anoFabricacao, uso, assentos,motor, variacao,preco,status});
                } while (rs.next());
            }


        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "error in querry " + ex.getMessage());

        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(rootPane, "error in connection" + ex.getMessage());

    }

}//GEN-LAST:event_jButton3ActionPerformed

private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jComboBox2ActionPerformed

private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated

    String path = "jdbc:mysql://localhost/";
    String place = "VcAluga";

    try {
        Class.forName("com.mysql.jdbc.Driver");

        Connection myconnect = DriverManager.getConnection(path + place,  "fam1709","17091991");
        try {
            String q = "select marca from veiculo";
            PreparedStatement mystatement = myconnect.prepareStatement(q);


            ResultSet myresult = mystatement.executeQuery();
            jComboBox2.addItem("Selecionar Marca");
            if (myresult.next()) {
                do {
                    jComboBox2.addItem(myresult.getString(1));
                } while (myresult.next());

            } else {
                jComboBox2.addItem("No Company availble");

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "error in Query" + ex.getMessage());
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(rootPane, "error in connection" + ex.getMessage());

    }





}//GEN-LAST:event_formInternalFrameActivated
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}